name: sign-xcframework
description: Signs an XCFramework with the Ionic Distribution ID Certificate
inputs:
  cert-token:
    description: The token containing the information needed to sign the xcframework
    required: true
  xcframework-path:
    description: Path to the xcframework
    required: true
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/sign.sh ${{ inputs.cert-token }} ${{ inputs.xcframework-path }}
      shell: bash
